//
// Created by 赵英坤 on 2019/9/18.
//

#ifndef LEARNCPPROJECT_TESTPRODUCTERANDCONSUMER_H
#define LEARNCPPROJECT_TESTPRODUCTERANDCONSUMER_H

void testPC();

#endif //LEARNCPPROJECT_TESTPRODUCTERANDCONSUMER_H
